//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actividad_Integradora_7_Problema_5.ServiceReservaciones {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReservaciones.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarReservacion", ReplyAction="*")]
        Actividad_Integradora_7_Problema_5.ServiceReservaciones.ConsultarReservacionResponse ConsultarReservacion(Actividad_Integradora_7_Problema_5.ServiceReservaciones.ConsultarReservacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultarReservacion", ReplyAction="*")]
        System.Threading.Tasks.Task<Actividad_Integradora_7_Problema_5.ServiceReservaciones.ConsultarReservacionResponse> ConsultarReservacionAsync(Actividad_Integradora_7_Problema_5.ServiceReservaciones.ConsultarReservacionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarReservacion", ReplyAction="*")]
        Actividad_Integradora_7_Problema_5.ServiceReservaciones.AgregarReservacionResponse AgregarReservacion(Actividad_Integradora_7_Problema_5.ServiceReservaciones.AgregarReservacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarReservacion", ReplyAction="*")]
        System.Threading.Tasks.Task<Actividad_Integradora_7_Problema_5.ServiceReservaciones.AgregarReservacionResponse> AgregarReservacionAsync(Actividad_Integradora_7_Problema_5.ServiceReservaciones.AgregarReservacionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarReservacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarReservacion", Namespace="http://tempuri.org/", Order=0)]
        public Actividad_Integradora_7_Problema_5.ServiceReservaciones.ConsultarReservacionRequestBody Body;
        
        public ConsultarReservacionRequest() {
        }
        
        public ConsultarReservacionRequest(Actividad_Integradora_7_Problema_5.ServiceReservaciones.ConsultarReservacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarReservacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string valor;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fecha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string hora;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string dias;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string costo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string personas;
        
        public ConsultarReservacionRequestBody() {
        }
        
        public ConsultarReservacionRequestBody(string valor, string nombre, string fecha, string hora, string dias, string costo, string personas) {
            this.valor = valor;
            this.nombre = nombre;
            this.fecha = fecha;
            this.hora = hora;
            this.dias = dias;
            this.costo = costo;
            this.personas = personas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarReservacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultarReservacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Actividad_Integradora_7_Problema_5.ServiceReservaciones.ConsultarReservacionResponseBody Body;
        
        public ConsultarReservacionResponse() {
        }
        
        public ConsultarReservacionResponse(Actividad_Integradora_7_Problema_5.ServiceReservaciones.ConsultarReservacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultarReservacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ConsultarReservacionResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fecha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string hora;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string dias;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string costo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string personas;
        
        public ConsultarReservacionResponseBody() {
        }
        
        public ConsultarReservacionResponseBody(bool ConsultarReservacionResult, string nombre, string fecha, string hora, string dias, string costo, string personas) {
            this.ConsultarReservacionResult = ConsultarReservacionResult;
            this.nombre = nombre;
            this.fecha = fecha;
            this.hora = hora;
            this.dias = dias;
            this.costo = costo;
            this.personas = personas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarReservacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarReservacion", Namespace="http://tempuri.org/", Order=0)]
        public Actividad_Integradora_7_Problema_5.ServiceReservaciones.AgregarReservacionRequestBody Body;
        
        public AgregarReservacionRequest() {
        }
        
        public AgregarReservacionRequest(Actividad_Integradora_7_Problema_5.ServiceReservaciones.AgregarReservacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarReservacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fecha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string hora;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string dias;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string costo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string personas;
        
        public AgregarReservacionRequestBody() {
        }
        
        public AgregarReservacionRequestBody(string nombre, string fecha, string hora, string dias, string costo, string personas) {
            this.nombre = nombre;
            this.fecha = fecha;
            this.hora = hora;
            this.dias = dias;
            this.costo = costo;
            this.personas = personas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarReservacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarReservacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Actividad_Integradora_7_Problema_5.ServiceReservaciones.AgregarReservacionResponseBody Body;
        
        public AgregarReservacionResponse() {
        }
        
        public AgregarReservacionResponse(Actividad_Integradora_7_Problema_5.ServiceReservaciones.AgregarReservacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarReservacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AgregarReservacionResult;
        
        public AgregarReservacionResponseBody() {
        }
        
        public AgregarReservacionResponseBody(bool AgregarReservacionResult) {
            this.AgregarReservacionResult = AgregarReservacionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Actividad_Integradora_7_Problema_5.ServiceReservaciones.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Actividad_Integradora_7_Problema_5.ServiceReservaciones.WebService1Soap>, Actividad_Integradora_7_Problema_5.ServiceReservaciones.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Actividad_Integradora_7_Problema_5.ServiceReservaciones.ConsultarReservacionResponse Actividad_Integradora_7_Problema_5.ServiceReservaciones.WebService1Soap.ConsultarReservacion(Actividad_Integradora_7_Problema_5.ServiceReservaciones.ConsultarReservacionRequest request) {
            return base.Channel.ConsultarReservacion(request);
        }
        
        public bool ConsultarReservacion(string valor, ref string nombre, ref string fecha, ref string hora, ref string dias, ref string costo, ref string personas) {
            Actividad_Integradora_7_Problema_5.ServiceReservaciones.ConsultarReservacionRequest inValue = new Actividad_Integradora_7_Problema_5.ServiceReservaciones.ConsultarReservacionRequest();
            inValue.Body = new Actividad_Integradora_7_Problema_5.ServiceReservaciones.ConsultarReservacionRequestBody();
            inValue.Body.valor = valor;
            inValue.Body.nombre = nombre;
            inValue.Body.fecha = fecha;
            inValue.Body.hora = hora;
            inValue.Body.dias = dias;
            inValue.Body.costo = costo;
            inValue.Body.personas = personas;
            Actividad_Integradora_7_Problema_5.ServiceReservaciones.ConsultarReservacionResponse retVal = ((Actividad_Integradora_7_Problema_5.ServiceReservaciones.WebService1Soap)(this)).ConsultarReservacion(inValue);
            nombre = retVal.Body.nombre;
            fecha = retVal.Body.fecha;
            hora = retVal.Body.hora;
            dias = retVal.Body.dias;
            costo = retVal.Body.costo;
            personas = retVal.Body.personas;
            return retVal.Body.ConsultarReservacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Actividad_Integradora_7_Problema_5.ServiceReservaciones.ConsultarReservacionResponse> Actividad_Integradora_7_Problema_5.ServiceReservaciones.WebService1Soap.ConsultarReservacionAsync(Actividad_Integradora_7_Problema_5.ServiceReservaciones.ConsultarReservacionRequest request) {
            return base.Channel.ConsultarReservacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Actividad_Integradora_7_Problema_5.ServiceReservaciones.ConsultarReservacionResponse> ConsultarReservacionAsync(string valor, string nombre, string fecha, string hora, string dias, string costo, string personas) {
            Actividad_Integradora_7_Problema_5.ServiceReservaciones.ConsultarReservacionRequest inValue = new Actividad_Integradora_7_Problema_5.ServiceReservaciones.ConsultarReservacionRequest();
            inValue.Body = new Actividad_Integradora_7_Problema_5.ServiceReservaciones.ConsultarReservacionRequestBody();
            inValue.Body.valor = valor;
            inValue.Body.nombre = nombre;
            inValue.Body.fecha = fecha;
            inValue.Body.hora = hora;
            inValue.Body.dias = dias;
            inValue.Body.costo = costo;
            inValue.Body.personas = personas;
            return ((Actividad_Integradora_7_Problema_5.ServiceReservaciones.WebService1Soap)(this)).ConsultarReservacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Actividad_Integradora_7_Problema_5.ServiceReservaciones.AgregarReservacionResponse Actividad_Integradora_7_Problema_5.ServiceReservaciones.WebService1Soap.AgregarReservacion(Actividad_Integradora_7_Problema_5.ServiceReservaciones.AgregarReservacionRequest request) {
            return base.Channel.AgregarReservacion(request);
        }
        
        public bool AgregarReservacion(string nombre, string fecha, string hora, string dias, string costo, string personas) {
            Actividad_Integradora_7_Problema_5.ServiceReservaciones.AgregarReservacionRequest inValue = new Actividad_Integradora_7_Problema_5.ServiceReservaciones.AgregarReservacionRequest();
            inValue.Body = new Actividad_Integradora_7_Problema_5.ServiceReservaciones.AgregarReservacionRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.fecha = fecha;
            inValue.Body.hora = hora;
            inValue.Body.dias = dias;
            inValue.Body.costo = costo;
            inValue.Body.personas = personas;
            Actividad_Integradora_7_Problema_5.ServiceReservaciones.AgregarReservacionResponse retVal = ((Actividad_Integradora_7_Problema_5.ServiceReservaciones.WebService1Soap)(this)).AgregarReservacion(inValue);
            return retVal.Body.AgregarReservacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Actividad_Integradora_7_Problema_5.ServiceReservaciones.AgregarReservacionResponse> Actividad_Integradora_7_Problema_5.ServiceReservaciones.WebService1Soap.AgregarReservacionAsync(Actividad_Integradora_7_Problema_5.ServiceReservaciones.AgregarReservacionRequest request) {
            return base.Channel.AgregarReservacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Actividad_Integradora_7_Problema_5.ServiceReservaciones.AgregarReservacionResponse> AgregarReservacionAsync(string nombre, string fecha, string hora, string dias, string costo, string personas) {
            Actividad_Integradora_7_Problema_5.ServiceReservaciones.AgregarReservacionRequest inValue = new Actividad_Integradora_7_Problema_5.ServiceReservaciones.AgregarReservacionRequest();
            inValue.Body = new Actividad_Integradora_7_Problema_5.ServiceReservaciones.AgregarReservacionRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.fecha = fecha;
            inValue.Body.hora = hora;
            inValue.Body.dias = dias;
            inValue.Body.costo = costo;
            inValue.Body.personas = personas;
            return ((Actividad_Integradora_7_Problema_5.ServiceReservaciones.WebService1Soap)(this)).AgregarReservacionAsync(inValue);
        }
    }
}
